<?php


module_load_include('inc', 'bibdk_reviews', 'bibdk_review.material_review');
module_load_include('inc', 'bibdk_reviews', 'bibdk_review.article_review');

/** Implements hook_ting_openformat_getobject_params_alter
 * @return array
 */
function bibdk_reviews_ting_openformat_getobject_params_alter($params) {

  $params['relationData'] = 'uri';
}


/** Implements hook_thme
 * @return array
 */
function bibdk_reviews_theme(){
  return array(
    'bibdk-review-material-review' => array(
      'variables' => array(
        'titles' => array(),
        'sections' => array(),
        'authors' => array(),
      ),
      'template' => 'theme/bibdk_review_material_review',
    ),
   'bibdk_review_article_review' => array(
      'variables' => array(
        'title' => '',
        'publisher' => '',
        'creator' => '',
        'rating' => '',
        'link' => '',
      ),
      'template' => 'theme/bibdk-review-article-review',
    ),
   'bibdk_review_rating' => array(
      'variables' => array(
        'rating' => '',
        'total_stars' => '',
      ),
      //'template' => 'theme/bibdk-review-rating',
    ),
  );
}


/** Form with a trigger button to load reviews for works
 *
 * @param $form
 * @param $form_state
 * @param $ids
 * @return array
 */
function bibdk_reviews_ajax_trigger_form($form, &$form_state, $manifestations_ids, $submit_function) {
  $ids = $manifestations_ids;

  if (!isset($ids) || count($ids) == 0) {
    $form['no_reviews'] = array(
      '#markup' => t('no_reviews_for_this_work'),
    );
  }
  else {
    $form['ajax_trigger'] = array(
      '#type' => 'submit',
      '#value' => 'get-reviews',
      '#ajax' => array(
        'callback' => $submit_function,
        'event' => 'click',
      ),
      '#ids' => $ids,
      '#attributes' => array(
        'class' => array('visuallyhidden ajax-trigger')
      ),
      '#attached' => array(
        'js' => array(drupal_get_path('module', 'bibdk_reviews') . '/js/bibdk_reviews.js'),
      ),
    );

  }
  return $form;
}

function _bibdk_reviews_get_work_entity_from_manifestation_ids($manifestations_ids) {
  $params = array(
    'objectFormat' => 'dkabm',
    //'includeHoldingsCount' => false,
    'relationData' => 'full',
  );

  return reset(ting_openformat_get_manifestations($manifestations_ids, $params));

}




/** Implements hook_worktabs_items
 * @param $tabs
 * @param $entity
 * @return array
 */
function bibdk_reviews_worktabs_items($tabs, $entity) {

  // following is commented out, because we don't have the relations´in hand at this point
  /*
  $review_ids = $entity->getMaterialReview();
  $trigger_form = drupal_get_form('bibdk_reviews_ajax_trigger_form', $review_ids);
  */

  $manifestation_ids = array_keys($entity->getManifestations());
  $trigger_form = drupal_get_form('bibdk_reviews_ajax_trigger_form', $manifestation_ids, 'bibdk_reviews_material_ajax_trigger_form_submit');


  $tabs['reviews']['material_review'] = array(
    'title' => t('material review'),
    'rendered' => drupal_render($trigger_form),
    'weight' => 0,
  );

  $trigger_form = drupal_get_form('bibdk_reviews_ajax_trigger_form', $manifestation_ids, 'bibdk_reviews_article_ajax_trigger_form_submit');
  $tabs['reviews']['other_review'] = array(
    'title' => t('other review'),
    'rendered' => drupal_render($trigger_form),
    'weight' => 0,
  );

  return $tabs;
}
